// ------------------------------
// GLOBAL CACHE
// ------------------------------
let cachedEmployees = [];
let allTrips = [];
let allTimeOffRequests = [];

// XSS Protection utility
function escapeHtml(unsafe) {
  if (!unsafe && unsafe !== 0) return "";
  return String(unsafe)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// ------------------------------
// INITIALIZATION
// ------------------------------
document.addEventListener("DOMContentLoaded", async () => {
  const loader = document.getElementById("loading-overlay");
  loader?.classList.add("visible");

  const startTime = Date.now();
  try {
    await fetchEmployees();
    setupSearch();
    initModals();
    initSyncButton(); // optional, guarded
    initCreateAccountForm(); // optional, guarded
  } finally {
    const elapsed = Date.now() - startTime;
    const remaining = Math.max(0, 500 - elapsed);
    setTimeout(() => loader?.classList.remove("visible"), remaining);
  }
});

// ------------------------------
// EMPLOYEE ID / PIN / AUTH PASSWORD RULES
// employee_id   = EMP0008
// username      = employee_id
// employee_pin4 = generated by DB from last 4 digits of employee_id
// auth_password = EMP + employee_pin4
// ------------------------------
function parseEmpNumber(employeeId) {
  if (!employeeId) return null;
  const s = String(employeeId).trim().toUpperCase();
  if (!s.startsWith("EMP")) return null;
  const n = parseInt(s.slice(3), 10);
  return Number.isFinite(n) ? n : null;
}

function computeNextEmployeeId() {
  const START = 8;
  let max = START - 1;

  for (const emp of cachedEmployees) {
    const n = parseEmpNumber(emp.employee_id);
    if (n !== null && n > max) max = n;
  }

  const next = max + 1;
  return `EMP${String(next).padStart(4, "0")}`;
}

function pinFromEmployeeId(employeeId) {
  return String(employeeId || "").slice(-4);
}

function authPasswordFromPin(pin4) {
  return `EMP${String(pin4 || "").trim()}`;
}

// ------------------------------
// SET AUTO FIELDS IN ADD MODAL
// ------------------------------
async function setAddModalAutoFields() {
  const empIdEl = document.getElementById("empEmployeeId");
  const userEl = document.getElementById("empUsername");
  const pinEl = document.getElementById("empPin4");
  const passEl = document.getElementById("empTempPassword");

  if (!empIdEl || !userEl || !pinEl || !passEl) {
    console.warn("Missing empEmployeeId/empUsername/empPin4/empTempPassword inputs in Add modal.");
    return;
  }

  // Placeholder while fetching
  empIdEl.value = "Fetching...";
  userEl.value = "Fetching...";

  try {
    const employee_id = await window.api.getNextEmployeeId();
    const employee_pin4 = pinFromEmployeeId(employee_id);
    const auth_password = authPasswordFromPin(employee_pin4);

    empIdEl.value = employee_id;
    userEl.value = employee_id;
    pinEl.value = employee_pin4; // display only
    passEl.value = auth_password;
  } catch (err) {
    console.error("Failed to get next employee ID:", err);
    empIdEl.value = "EMP0000";
  }
}


// ------------------------------
// SEARCH
// ------------------------------
function setupSearch() {
  const searchInput = document.getElementById("searchInput");
  if (!searchInput) return;

  searchInput.addEventListener("input", () => {
    renderEmployees(allEmployees);
  });
}

// ------------------------------
// DELETE EMPLOYEE
// ------------------------------
async function deleteEmployee(id) {
  if (!confirm("Are you sure you want to delete this employee?")) return;

  try {
    await window.api.deleteEmployee(id);
    await fetchEmployees();
  } catch (err) {
    console.error("Delete error:", err);
    alert("Failed to delete employee. Check console for details.");
  }
}

// ------------------------------
// MODALS (OPEN / CLOSE)
// ------------------------------
function initModals() {
  const addModal = document.getElementById("addEmployeeModal");
  const editModal = document.getElementById("editEmployeeModal");

  const addBtn = document.getElementById("addEmployeeBtn");
  const closeAdd = document.getElementById("closeAddModalBtn");
  const closeEdit = document.getElementById("closeEditModalBtn");

  if (addBtn && addModal) {
    addBtn.addEventListener("click", async () => {
      addModal.style.display = "flex";
      await setAddModalAutoFields();
    });
  }

  if (closeAdd && addModal) {
    closeAdd.addEventListener("click", () => {
      addModal.style.display = "none";
    });
  }

  if (closeEdit && editModal) {
    closeEdit.addEventListener("click", () => {
      editModal.style.display = "none";
    });
  }

  window.addEventListener("click", (e) => {
    if (addModal && e.target === addModal) addModal.style.display = "none";
    if (editModal && e.target === editModal) editModal.style.display = "none";
  });
}

// ------------------------------
// ADD EMPLOYEE
// ------------------------------
const employeeTableBody = document.getElementById("employeeTableBody");
const searchInput = document.getElementById("searchInput");
const addEmployeeBtn = document.getElementById("addEmployeeBtn");
const addEmployeeModal = document.getElementById("addEmployeeModal");
const closeAddModalBtn = document.getElementById("closeAddModalBtn");
const addEmployeeForm = document.getElementById("addEmployeeForm");

let allEmployees = [];

async function fetchEmployees() {
  try {
    const [employees, trips, requests] = await Promise.all([
      window.api.getEmployees(),
      window.api.getTrips(),
      window.api.getTimeOffRequests()
    ]);
    
    allEmployees = employees;
    allTrips = trips;
    allTimeOffRequests = requests;
    cachedEmployees = allEmployees; 
    renderEmployees(allEmployees);
  } catch (err) {
    console.error("❌ Error fetching employees:", err);
  }
}

function getDynamicStatus(emp, requests, trips, date = new Date()) {
  let status = emp.status || "available";
  const empRole = (emp.role || emp.position || "").trim().toLowerCase();

  // Time-off checks (highest priority)
  const approvedTimeOff = requests.find(r =>
    String(r.employee_id) === String(emp.id) &&
    r.status.toLowerCase() === "approved" &&
    new Date(r.start_date) <= date &&
    date <= new Date(r.end_date)
  );
  if (approvedTimeOff) return "unavailable";

  const pendingTimeOff = requests.find(r =>
    String(r.employee_id) === String(emp.id) &&
    r.status.toLowerCase() === "pending" &&
    new Date(r.start_date) <= date &&
    date <= new Date(r.end_date)
  );
  if (pendingTimeOff) status = "partially";

  // Trip check (only drivers)
  if (empRole === "driver") {
    const empTrips = trips.filter(t => String(t.driver_id) === String(emp.id));
    for (let t of empTrips) {
      const start = new Date(t.pickup_time);
      const end = new Date(t.delivery_time);
      const tripStatus = (t.status || "").trim().toLowerCase();

      // Currently on a trip => unavailable
      if (start <= date && date <= end && ["in transit", "in-transit"].includes(tripStatus)) {
        return "unavailable";
      }

      // Future or pending trips => busy
      if (["pending", "scheduled", "delayed"].includes(tripStatus) && start >= date) {
        if (status !== "unavailable") status = "busy";
      }
    }
  }
  return status;
}

function renderEmployees(employees) {
  employeeTableBody.innerHTML = "";

  const filterText = searchInput?.value?.trim().toLowerCase() || "";

  if (!filterText) {
    employeeTableBody.innerHTML = `<tr><td colspan="6" style="text-align:center; padding: 40px; color: var(--text-muted);">Please use the search bar to display records.</td></tr>`;
    return;
  }

  const filteredEmployees = employees.filter(emp => {
      const searchableText = `${emp.full_name} ${emp.employee_id} ${emp.id} ${emp.position} ${emp.department} ${emp.email}`.toLowerCase();
      return searchableText.includes(filterText);
  });

  if (filteredEmployees.length === 0) {
    employeeTableBody.innerHTML = `<tr><td colspan="6" style="text-align:center; padding: 40px; color: var(--text-muted);">No employees found.</td></tr>`;
    return;
  }

  filteredEmployees.forEach((emp) => {
    const tr = document.createElement("tr");
    const dynamicStatus = getDynamicStatus(emp, allTimeOffRequests, allTrips);

    tr.innerHTML = `
      <td>
        <div style="display: flex; align-items: center; gap: 12px;">
           <div style="width: 36px; height: 36px; background: #eff6ff; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 700; color: var(--primary); font-size: 12px;">
              ${escapeHtml(emp.full_name?.split(' ').map(n => n[0]).join('') || '??')}
           </div>
           <div>
              <div style="font-weight: 700; color: var(--text-main);">${escapeHtml(emp.full_name)}</div>
              <div style="font-size: 11px; color: var(--text-light);">ID: ${escapeHtml(emp.employee_id || emp.id)}</div>
           </div>
        </div>
      </td>
      <td>
        <div style="font-size: 13px; color: var(--text-main);">${escapeHtml(emp.email)}</div>
        <div style="font-size: 11px; color: var(--text-muted);">${escapeHtml(emp.phone || 'No phone')}</div>
      </td>
      <td>
        <div style="font-weight: 600; color: var(--text-main);">${escapeHtml(emp.position)}</div>
        <div style="font-size: 11px; color: var(--text-muted);">${escapeHtml(emp.department)}</div>
      </td>
      <td>
        <span class="badge ${getStatusBadgeClass(dynamicStatus)}">${escapeHtml(dynamicStatus)}</span>
      </td>
      <td style="color: var(--text-muted); font-size: 13px;">
        ${emp.hire_date ? new Date(emp.hire_date).toLocaleDateString() : 'N/A'}
      </td>
      <td style="text-align: right;">
        <button onclick="openEditModal('${emp.id}')" style="background: none; border: none; color: var(--primary); cursor: pointer; padding: 4px;"><i data-lucide="edit-3" size="16"></i></button>
        <button onclick="deleteEmployee('${emp.id}')" style="background: none; border: none; color: var(--error); cursor: pointer; padding: 4px;"><i data-lucide="trash-2" size="16"></i></button>
      </td>
    `;
    employeeTableBody.appendChild(tr);
  });

  if (window.lucide) lucide.createIcons();
}

function getStatusBadgeClass(status) {
  switch (status?.toLowerCase()) {
    case 'available': case 'active': return 'badge-success';
    case 'in-use': case 'busy': return 'badge-info';
    case 'unavailable': case 'on leave': return 'badge-error';
    case 'pending': return 'badge-warning';
    default: return 'badge-info';
  }
}

// NOTE: Search, modal open/close, and form listeners are handled inside
// DOMContentLoaded > setupSearch() and initModals() to avoid duplicate registration.
// Do NOT add top-level listeners here.

// --- FORM SUBMISSION ---
addEmployeeForm.addEventListener("submit", async (e) => {
  e.preventDefault();

  const full_name = document.getElementById("empName")?.value?.trim();
  const email = document.getElementById("empEmail")?.value?.trim();
  const phone = document.getElementById("empPhone")?.value?.trim();
  const position = document.getElementById("empPosition")?.value?.trim();
  const department = document.getElementById("empDept")?.value?.trim();
  const status = document.getElementById("empStatus")?.value;
  
  const employee_id = document.getElementById("empEmployeeId")?.value;
  const auth_password = document.getElementById("empTempPassword")?.value;
  const employee_pin4 = document.getElementById("empPin4")?.value;
  
  const daily_rate = parseFloat(document.getElementById("empDailyRate")?.value || "0");
  const salary = parseFloat(document.getElementById("empSalary")?.value || "0");

  // Frontend validation
  if (!full_name) {
    return alert("Name is required.");
  }
  if (!email) {
    return alert("Email is required.");
  }
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return alert("Please enter a valid email address.");
  }
  if (phone && !/^[\d\s\+\-\(\)]{7,20}$/.test(phone)) {
    return alert("Please enter a valid phone number (digits, spaces, +, -, () only, 7-20 chars).");
  }
  if (daily_rate < 0) {
    return alert("Daily rate cannot be negative.");
  }
  if (salary < 0) {
    return alert("Salary cannot be negative.");
  }

  const payload = {
    employee_id,
    full_name,
    email,
    phone: phone || null,
    status: status || "available",
    position: position || "Driver",
    department: department || "Operations",
    auth_email: email,
    auth_password,
    daily_rate,
    salary
  };

  console.log("createEmployee payload:", payload);
  console.log("derived values:", {
    employee_id,
    employee_pin4,
    auth_password,
  });

  try {
    const result = await window.api.createEmployee(payload);

    if (!result?.ok) {
      alert("Failed to add employee: " + (result?.message || "Unknown error"));
      return;
    }

    alert(
      `Employee Created!\nEmployee ID: ${employee_id}\nPIN: ${employee_pin4}\nAuth Password: ${auth_password}`
    );

    addEmployeeModal.style.display = "none";
    addEmployeeForm.reset();
    await setAddModalAutoFields();

    await fetchEmployees();
  } catch (err) {
    console.error(err);
    alert("Error adding employee. Check console.");
  }
});

// ------------------------------
// CREATE ACCOUNT FORM (OPTIONAL / GUARDED)
// If you no longer use this modal/form, this safely does nothing.
// ------------------------------
function initCreateAccountForm() {
  const form = document.getElementById("createAccountForm");
  if (!form) return;

  form.addEventListener("submit", async (e) => {
    e.preventDefault();

    const empId = document.getElementById("createAccEmpId")?.value;
    const username = document.getElementById("accUsername")?.value.trim();
    const pin = document.getElementById("accPassword")?.value.trim();

    const statusEl = document.getElementById("createAccountStatus");
    if (statusEl) {
      statusEl.innerText = " Creating account...";
      statusEl.style.color = "#475569";
    }

    if (!empId || !username || !pin) {
      if (statusEl) {
        statusEl.innerText = " Missing employee, username, or PIN.";
        statusEl.style.color = "red";
      }
      return;
    }

    const authPassword = authPasswordFromPin(pin);

    try {
      if (!window.api.createEmployeeAccount) {
        throw new Error("createEmployeeAccount API is not available.");
      }

      const res = await window.api.createEmployeeAccount(empId, username, authPassword);

      if (res?.success) {
        if (statusEl) {
          statusEl.innerText = " Account created & linked!";
          statusEl.style.color = "green";
        }
        await fetchEmployees();
      } else {
        if (statusEl) {
          statusEl.innerText = " " + (res?.error || "Failed to create account.");
          statusEl.style.color = "red";
        }
      }
    } catch (err) {
      console.error(err);
      if (statusEl) {
        statusEl.innerText = " Error creating account. Check console.";
        statusEl.style.color = "red";
      }
    }
  });
}

// ------------------------------
// EDIT EMPLOYEE FORM SUBMISSION
// ------------------------------
const editEmployeeForm = document.getElementById("editEmployeeForm");
if (editEmployeeForm) {
  editEmployeeForm.addEventListener("submit", async (e) => {
    e.preventDefault();
    const id = document.getElementById("editEmpId").value;
    const full_name = document.getElementById("editEmpName").value?.trim();
    const email = document.getElementById("editEmpEmail").value?.trim();
    const phone = document.getElementById("editEmpPhone").value?.trim();
    const daily_rate = parseFloat(document.getElementById("editEmpDailyRate")?.value || "0");
    const salary = parseFloat(document.getElementById("editEmpSalary")?.value || "0");

    // Validation
    if (!full_name) return alert("Name is required.");
    if (!email) return alert("Email is required.");
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) return alert("Please enter a valid email address.");
    if (phone && !/^[\d\s\+\-\(\)]{7,20}$/.test(phone)) {
      return alert("Please enter a valid phone number.");
    }
    if (daily_rate < 0) return alert("Daily rate cannot be negative.");
    if (salary < 0) return alert("Salary cannot be negative.");

    const payload = {
      full_name,
      email,
      phone,
      position: document.getElementById("editEmpPosition").value,
      department: document.getElementById("editEmpDept").value,
      status: document.getElementById("editEmpStatus").value,
      daily_rate,
      salary,
    };

    try {
      const result = await window.api.updateEmployee(id, payload);
      if (result.error) {
        alert("Update failed: " + result.error);
      } else {
        alert("Employee updated successfully!");
        document.getElementById("editEmployeeModal").style.display = "none";
        await fetchEmployees();
      }
    } catch (err) {
      console.error("Update error:", err);
      alert("Error updating employee.");
    }
  });
}

// ------------------------------
// OPEN EDIT MODAL
// ------------------------------
async function openEditModal(id) {
  const editModal = document.getElementById("editEmployeeModal");
  if (!editModal) return;

  try {
    const emp = await window.api.getEmployeeById(id);
    if (!emp) return alert("Employee not found");

    const editEmpId = document.getElementById("editEmpId");
    const editEmpName = document.getElementById("editEmpName");
    const editEmpEmail = document.getElementById("editEmpEmail");
    const editEmpPhone = document.getElementById("editEmpPhone");
    const editEmpPosition = document.getElementById("editEmpPosition");
    const editEmpDept = document.getElementById("editEmpDept");
    const editEmpStatus = document.getElementById("editEmpStatus");

    if (editEmpId) editEmpId.value = emp.id;
    if (editEmpName) editEmpName.value = emp.full_name || "";
    if (editEmpEmail) editEmpEmail.value = emp.email || "";
    if (editEmpPhone) editEmpPhone.value = emp.phone || "";
    if (editEmpPosition) editEmpPosition.value = emp.position || "";
    if (editEmpDept) editEmpDept.value = emp.department || "";
    if (editEmpStatus) editEmpStatus.value = (emp.status || "available").toLowerCase();
    
    const editEmpDailyRate = document.getElementById("editEmpDailyRate");
    const editEmpSalary = document.getElementById("editEmpSalary");
    if (editEmpDailyRate) editEmpDailyRate.value = emp.daily_rate || 0;
    if (editEmpSalary) editEmpSalary.value = emp.salary || 0;

    editModal.style.display = "flex";
  } catch (err) {
    console.error("Error opening edit modal:", err);
    alert("Failed to load employee data. Check console.");
  }
}

// ------------------------------
// SYNC EXISTING ACCOUNT BY EMAIL (OPTIONAL / GUARDED)
// ------------------------------
function initSyncButton() {
  const syncBtn = document.getElementById("syncAccountBtn");
  if (!syncBtn) return;

  syncBtn.addEventListener("click", async (e) => {
    e.preventDefault();

    const empId = document.getElementById("editEmpId")?.value;
    const email = document.getElementById("editEmpEmail")?.value;
    const statusEl = document.getElementById("syncStatus");

    if (!empId || !email) {
      if (statusEl) {
        statusEl.innerText = " Missing employee or email.";
        statusEl.style.color = "red";
      }
      return;
    }

    if (statusEl) {
      statusEl.innerText = " Checking existing account...";
      statusEl.style.color = "#475569";
    }

    try {
      if (!window.api.syncEmployeeAccountByEmail) {
        throw new Error("syncEmployeeAccountByEmail API is not available.");
      }

      const result = await window.api.syncEmployeeAccountByEmail(empId, email);

      if (result?.success) {
        if (statusEl) {
          statusEl.innerText = " Account synced successfully!";
          statusEl.style.color = "green";
        }
        await fetchEmployees();
      } else {
        if (statusEl) {
          statusEl.innerText = " " + (result?.error || "Sync failed.");
          statusEl.style.color = "red";
        }
      }
    } catch (err) {
      console.error(err);
      if (statusEl) {
        statusEl.innerText = " Sync failed. Check console.";
        statusEl.style.color = "red";
      }
    }
  });
}